# Generated by Django 5.2.3 on 2025-07-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField()),
                ('recipe_description', models.TextField()),
                ('receipe', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
