# Generated by Django 5.2.3 on 2025-08-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe',
            new_name='receipe_image',
        ),
    ]
