# Generated by Django 5.2.3 on 2025-09-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_receipe_receipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='recipe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='recipe_name',
            new_name='receipe_name',
        ),
    ]
